/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import shiny from "assets/matcaps/shiny.png";

/**
 * This line was manually added to help parcel import the file
 */
const downloadUrl = new URL(
  "../../assets/models/Astronaut.glb",
  import.meta.url
);

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    mask: THREE.Mesh;
  };
  materials: {
    main: THREE.MeshStandardMaterial;
    mask: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    downloadUrl.href
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.body.geometry}
        material={materials.main}
        position={[0, 2.44, -0.01]}
      />
      <mesh geometry={nodes.mask.geometry}>
        <meshStandardMaterial roughness={0.2} metalness={0.8} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Astronaut.glb");
