/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

/**
 * This line was manually added to help parcel import the file
 */
const downloadUrl = new URL(
  "../../assets/models/Astronaut.glb",
  import.meta.url
);

type GLTFResult = GLTF & {
  nodes: {
    Astronaut_mesh: THREE.Mesh;
  };
  materials: {
    Astronaut_mat: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();

  /**
   * Manually Replace the useGLTF() paramater with "downloadUrl.href"
   * This will allow it to use the correctly hashed filename. e.g. Astronaut.a39a75bc.glb
   */
  const { nodes, materials } = useGLTF(
    downloadUrl.href
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Astronaut_mesh.geometry}
        material={materials.Astronaut_mat}
      />
    </group>
  );
}

useGLTF.preload("/Astronaut.glb");
